#!/bin/sh
# see PROTOCOL for details

nosock () {
    echo "Socket not found at $SAD_SOCK"
    echo "Did you start the SAD?\nsad -f $SAD_SOCK &"
}

[ -e "$SAD_SOCK" ] || nosock
printf "%s %s\\n" "$1" "$2" | nc -NU "$SAD_SOCK"
